name: 'Continuos Deployment'

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  deploy_cloud_run_service: 
    name: Deploy cloud run service
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/586822769377/locations/global/workloadIdentityPools/gthb-actions-pool/providers/judgiraldoot-challenge-mle
        service_account: sa-cd-gthb-actions@mle-challenge-419205.iam.gserviceaccount.com

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: delay-model
        image: us-docker.pkg.dev/mle-challenge-419205/gcr.io/delay_model:latest