name: 'Continuous Integration'

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run model tests
        run: |
          make model-test

      - name: Run API tests
        run: |
          make api-test

  trigger_continuous_deployment:
    name: Trigger Continuous Deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    needs: build_and_test
    steps:
      - name: Trigger Continuous Deployment Workflow
        uses: actions/workflow-dispatch@v2
        with:
          workflow: 'Continuous Deployment'